// ============================================================================
// replayTape — pure builder for a VHS tape that records a run's replay as a
// shareable gif + mp4. The choreography is fixed (load → autoplay → jump to the
// finale → reveal the 作品 card → quit), the transcript/output are parameters.
// Pure + node-safe so the (correctness-bearing) choreography unit-tests without
// ever shelling out to VHS. Honesty is unaffected: this only DRIVES the real
// interactive app — every frame VHS captures is the honest panel rendering.
// ============================================================================
export interface ReplayTapeOpts {
  /** Absolute path to the .jsonl / .json transcript. */
  transcript: string;
  /** Output .gif path (a sibling .mp4 is emitted alongside). */
  out: string;
  /** Project root (where src/tui/cli.tsx lives). */
  cwd: string;
  /** How long to record autoplay before jumping to the finale (default 10s). */
  autoplayMs?: number;
}

export function buildReplayTape(o: ReplayTapeOpts): string {
  const autoplay = o.autoplayMs ?? 6_000;
  const mp4 = o.out.replace(/\.gif$/i, '') + '.mp4';
  return [
    `# auto-generated by exportReplay — records ${o.transcript}`,
    `Output ${o.out}`,
    `Output ${mp4}`,
    `Set Shell "zsh"`,
    `Set Theme "Catppuccin Mocha"`,
    `Set FontSize 15`,
    `Set Width 960`,
    `Set Height 640`,
    `Set Padding 20`,
    ``,
    `Hide`,
    `Type "cd ${o.cwd} && clear"`,
    `Enter`,
    `Sleep 400ms`,
    `Show`,
    ``,
    `Type "npx tsx src/tui/cli.tsx ${o.transcript}"`,
    `Enter`,
    `Sleep 2.5s`,
    `Enter`, // bare Enter = play/pause → autoplay; the panel evolves, narration scrolls
    `Sleep ${autoplay}ms`,
    `Type "error"`, // jump to a real fire beat — the run's drama (no-op if none)
    `Enter`,
    `Sleep 2s`,
    `Type "error"`,
    `Enter`,
    `Sleep 2s`,
    `Type "end"`, // jump to the end → the inline 收工 finale
    `Enter`,
    `Sleep 2.5s`,
    `Type "card"`, // reveal the standalone 作品 card
    `Enter`,
    `Sleep 3s`,
    `Type "q"`,
    `Enter`,
    `Sleep 400ms`,
    ``,
  ].join('\n');
}
